### PR TITLE
Move registry creation to @BeforeEach in SampleTestRunner

### PR DESCRIPTION
**Pull request by ttddyy**
Simplifies the meter and observation registries management in `SampleTestRunner`

- Add "create[Meter|Observation]Registry" protected methods
- Initialize registries in @BeforeEach
- Remove the constructor that takes registries
- Each parameterized test creates a new registries
- Remove code to track used registries and @AfterAll to close them
- ~~Remove `TestConfigAccessor`~~
- Preserve and restore observation handlers for each run (for the usage of global registries instead of creating every time)

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
LGTM however I'd like @violetagg to take a look at this branch (if possible :pray: ) with what she has there in Reactor Netty.

**Comment by violetagg** [comment]
> LGTM however I'd like @violetagg to take a look at this branch (if possible 🙏 ) with what she has there in Reactor Netty.

I'll check it

**Comment by violetagg** [comment]
@ttddyy @marcingrzejszczak Do we need to recreate the registry for every test?

In Reactor Netty we have

```
	@BeforeAll
	static void setUp() throws CertificateException {
		...

		registry = new SimpleMeterRegistry();
		Metrics.addRegistry(registry);

		...
	}

	@AfterAll
	static void tearDown() {
		Metrics.removeRegistry(registry);
		registry.clear();
		registry.close();
	}
```

**Comment by marcingrzejszczak** [comment]
> In Reactor Netty we have

So in your cae you would override the `createMeterRegistry` method where you will essentially do what you do in your `setUp` method

> Also the change is breaking change :)

That is not possible because we typically do those just after the release ;) yeah... that's a breaking change

**Comment by violetagg** [comment]
LGTM ;)

**Pull request merged**
