### PR TITLE
Use annotation as parameter to avoid using string literal FQCN

### PR DESCRIPTION
**Pull request by quaff**
Align to `CountedAspect` in micrometer

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hey, thanks for the PR. What problem is this solving?

**Comment by quaff** [comment]
> Hey, thanks for the PR. What problem is this solving?

Polishing for keeping consistency with `CountedAspect`.

**Comment by shakuzen** [comment]
It's the same change as done in https://github.com/micrometer-metrics/micrometer/pull/3780 to resolve the problem mentioned in https://github.com/micrometer-metrics/micrometer/pull/3776

**Comment by shakuzen** [comment]
That said, I don't think we have the problem here since the annotation is not used as a method parameter. That's the same as we didn't have the issue with `TimedAspect` in micrometer, even though we had it with `CountedAspect`. So, I'll close this for now, unless we are having the issue with `SpanAspect` without these changes.

**Pull request closed without merging**
